// automatically generated by the FlatBuffers compiler, do not modify

package SprintSync.Schema

@Suppress("unused")
class TelemetryPayload private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val SessionTriggerRequest: UByte = 1u
        const val SessionTrigger: UByte = 2u
        const val SessionTimelineSnapshot: UByte = 3u
    }
}
